server:
  port: 9080

storage:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9082

user:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
